// DeadZoneVolume.cpp

#include "DeadZoneVolume.h"
#include "Components/BoxComponent.h"
#include "OXQuizGameMode.h"
#include "NoobGameCharacter.h" // [ผ๖มค] ฑโมธ ฤณธฏลอ ว์ด๕ ฦ๗วิ

ADeadZoneVolume::ADeadZoneVolume()
{
    PrimaryActorTick.bCanEverTick = false;

    CollisionComponent = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionComponent"));
    RootComponent = CollisionComponent;
    CollisionComponent->SetCollisionProfileName(TEXT("OverlapAllDynamic"));
    CollisionComponent->SetGenerateOverlapEvents(true);
}

void ADeadZoneVolume::BeginPlay()
{
    Super::BeginPlay();

    if (HasAuthority())
    {
        CollisionComponent->OnComponentBeginOverlap.AddDynamic(this, &ADeadZoneVolume::OnOverlapBegin);
        CachedGameMode = GetWorld() ? GetWorld()->GetAuthGameMode<AOXQuizGameMode>() : nullptr;
    }
}

void ADeadZoneVolume::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    if (!HasAuthority()) return;

    // [ผ๖มค] ANoobGameCharacterทฮ ฤณฝบฦร
    ANoobGameCharacter* PlayerCharacter = Cast<ANoobGameCharacter>(OtherActor);
    if (PlayerCharacter)
    {
        if (CachedGameMode)
        {
            CachedGameMode->HandlePlayerDeath(PlayerCharacter->GetController());
        }
        else
        {
            AOXQuizGameMode* GM = GetWorld() ? GetWorld()->GetAuthGameMode<AOXQuizGameMode>() : nullptr;
            if (GM)
            {
                CachedGameMode = GM;
                CachedGameMode->HandlePlayerDeath(PlayerCharacter->GetController());
            }
        }
    }
}