// DestroyObstacleVolume.cpp

#include "DestroyObstacleVolume.h"
#include "Components/BoxComponent.h"
#include "QuizObstacleBase.h" // [ม฿ฟไ] ภๅพึนฐภว บฮธ๐ ลฌทกฝบธฆ ฦ๗วิวีดฯดู.

ADestroyObstacleVolume::ADestroyObstacleVolume()
{
    PrimaryActorTick.bCanEverTick = false;

    CollisionComponent = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionComponent"));
    RootComponent = CollisionComponent;
    CollisionComponent->SetCollisionProfileName(TEXT("OverlapAllDynamic"));
    CollisionComponent->SetGenerateOverlapEvents(true);
}

void ADestroyObstacleVolume::BeginPlay()
{
    Super::BeginPlay();

    // ผญน๖ฟกผญธธ ฟภน๖ทฆ ภฬบฅฦฎธฆ ฐจม๖วีดฯดู.
    if (HasAuthority())
    {
        CollisionComponent->OnComponentBeginOverlap.AddDynamic(this, &ADestroyObstacleVolume::OnOverlapBegin);
    }
}

void ADestroyObstacleVolume::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    if (!HasAuthority())
    {
        return;
    }

    // ฟภน๖ทฆตศ พืลอฐก AQuizObstacleBase (ถวดย ฑื ภฺฝฤ ลฌทกฝบ)ภฮม๖ ศฎภฮวีดฯดู.
    AQuizObstacleBase* Obstacle = Cast<AQuizObstacleBase>(OtherActor);
    if (Obstacle)
    {
        // ภๅพึนฐภฬ ธยดูธ้ ม๏ฝร ฦฤฑซวีดฯดู.
        // Destroy()ดย ผญน๖ฟกผญ ศฃรโตวธ้ ภฺตฟภธทฮ ธ๐ต็ ลฌถ๓ภฬพ๐ฦฎฟกตต บนมฆตหดฯดู.
        Obstacle->Destroy();
    }
}